### ISSUE TITLE
Access to rr4---sn-qxaeenlz.googlevideo.com was denied (Status code: 403)

### ISSUE THREAD

**Issue by msalik42** [distubejs/ytdl-core#31] opened 2024-07-12 18:27 UTC
Ran the following code and it returns the video URLs, But when I try to access the files, it says access denied
const ytdl = require("@distube/ytdl-core");

ytdl.getBasicInfo("https://www.youtube.com/watch?v=eFe8bJ9e_FA").then((info) => {
	console.log(info);
});

**Comment by Pesepvtltd** [comment] 2024-07-13 11:11
have you got solution?

**Comment by skick1234** [comment] 2024-07-13 13:17
Due to recent youtube changes, you have to update to the latest version and download the stream from the same ip (and maybe the cookies). So if you want to download it from another client, you have to download it to your server and use other methods to download it from your server.

**Comment by Lampropoulosss** [comment] 2024-07-14 05:19
The issue is that I use the library on the server and I stream the video to my client myself. So, no other IP is used or anything. And it still, randomly, throws the error.

**Comment by skick1234** [comment] 2024-07-15 01:16
It seems youtube blocked downlpad from some itag, try changing the format, quality or filter options

**Comment by skick1234** [comment] 2024-07-15 01:17
It seems youtube blocked download some itag, try changing the format, quality or filter options

**Comment by mtripg6666tdr** [comment] 2024-07-15 16:23
FYI this issue may be related to [this issue](https://github.com/yt-dlp/yt-dlp/pull/10456)

**Comment by pauliusdotpro** [comment] 2024-07-18 06:13
I've also started getting issues

**Comment by Raul824** [comment] 2024-07-23 05:40
Well after fiddling with all permutations and combinations my assumption is there is some kind of protection on official channels or some strings.

So If i tried to getinfo of official music video the stream gives 403 error but if I do a getinfo of same song uploaded by someone else it works.

example.
 This doesn't work
https://www.youtube.com/watch?v=eFjjO_lhf9c

  This works
  https://www.youtube.com/watch?v=1i0i5lG6Ojc

@msalik42 
Try same thing on reaction video of the original video.

**Comment by vasanth-raja** [comment] 2024-07-24 06:57
403 fixed or any solutions yet?

**Comment by hjohnson12** [comment] 2024-07-26 22:26
Receiving 403 as well, which was fixed in 4.13.5 at first but now failing with the same error originally received in `ytdl-core` before switching to this fork of it. Any ideas?

**Comment by skick1234** [comment] 2024-07-30 17:35
I disabled cache on `4.13.7`, 403 is gone on my side but I don't know if it works on every video. Please try it and give feedback.

**Comment by ichsanulaulia** [comment] 2024-07-31 02:20
> I disabled cache on `4.13.7`, 403 is gone on my side but I don't know if it works on every video. Please try it and give feedback.

![image](https://github.com/user-attachments/assets/a061e03e-2755-4da1-adc1-0ebbec4f397b)
all format quality etc , 403 at all 
but this happend for some videos not all videos

**Comment by skick1234** [comment] 2024-07-31 02:22
> ![image](https://github.com/user-attachments/assets/a061e03e-2755-4da1-adc1-0ebbec4f397b)
> 
> all format quality etc , 403 at all 
> 
> but this happend for some videos not all videos 

Can you give me video url and your ip location as well?

**Comment by ichsanulaulia** [comment] 2024-07-31 02:51
> Can you give me video url and your ip location as well?

https://youtu.be/ozckx6_Z2a4
ip loc : Germany

**Comment by vasanth-raja** [comment] 2024-07-31 05:05
i switched to another package thats working at the moment, but docs are not easy to pick up
https://github.com/LuanRT/YouTube.js/blob/main/examples/download/index.ts

**Comment by skick1234** [comment] 2024-07-31 12:38
> > Can you give me video url and your ip location as well?
> 
> https://youtu.be/ozckx6_Z2a4 ip loc : Germany

Weird, I don't have any problem with it, can you test with browser headers like user-agent, origin,... and cookies.
I don't have 403 problem with your video

**Comment by ichsanulaulia** [comment] 2024-07-31 16:24
> > > Can you give me video url and your ip location as well?
> > 
> > 
> > https://youtu.be/ozckx6_Z2a4 ip loc : Germany
> 
> Weird, I don't have any problem with it, can you test with browser headers like user-agent, origin,... and cookies. I don't have 403 problem with your video

So there's no hope? I used everything you said ( user-agent origin, cookies ) for long time ago.

**Comment by fsholehan** [comment] 2024-08-01 01:50
Now, the local environment is also getting a 403 error.

**Comment by Lampropoulosss** [comment] 2024-08-01 12:55
> i switched to another package thats working at the moment, but docs are not easy to pick up https://github.com/LuanRT/YouTube.js/blob/main/examples/download/index.ts

Doens't work. Tried it with a few videos, for most of them it logs "server responded with not a 2.x.x status code

**Comment by alanor87** [comment] 2024-08-01 18:41
The same - 403 on some videos - others are being downloaded normally.

https://www.youtube.com/watch?v=6OZQ9Y2c1kY - works

https://www.youtube.com/watch?v=FavdK4bv56Q - does not work

**Comment by Lampropoulosss** [comment] 2024-08-01 21:26
Does this issue appear to other libraries / tools too? Such as yt-dlp, youtube-dl etc?

**Comment by nukeop** [comment] 2024-08-01 21:28
After I updated to the newest release, these problems are completely gone.

**Comment by fsholehan** [comment] 2024-08-01 22:47
> After I updated to the newest release, these problems are completely gone.

Yes, but with the same video, sometimes it returns a 403 error, and sometimes it works.

**Comment by yyildiz** [comment] 2024-08-02 00:02
Are you on the latest @fsholehan?

**Comment by nukeop** [comment] 2024-08-02 00:05
Suddenly 403s are back, with almost every single stream.

**Comment by fsholehan** [comment] 2024-08-02 00:36
> Are you on the latest @fsholehan?

Yes, I'm on the latest version

**Comment by skick1234** [comment] 2024-08-02 01:42
It looks like YouTube is conducting A/B testing to prevent bots. I’ll look into their anti-bot token and update the package after my working hours.

**Comment by Marbanz** [comment] 2024-08-02 08:03
I did some testing and found out that using cookies of a yt premium account doesn't give errors, while without cookies or with the cookies of a non premium account it gives the 403 error

**Comment by Brainicism** [comment] 2024-08-02 09:09
https://github.com/yt-dlp/yt-dlp/pull/10456 seems like a relevant fix, but not sure how easily portable this is?

**Comment by DevBelkin** [comment] 2024-08-04 02:33
> I did some testing and found out that using cookies of a yt premium account doesn't give errors, while without cookies or with the cookies of a non premium account it gives the 403 error

I also tried with the premium account and it works without any error.

**Comment by Brainicism** [comment] 2024-08-04 03:03
https://github.com/yt-dlp/yt-dlp/pull/10457 
Not sure if you've seen this already, yt-dlp mitigated this by swapping to a non-web client.

**Closed** 2024-08-04 12:30 UTC
Labels: bug

**Comment by jokerzhenghaonan** [comment] 2024-11-09 07:42
> > I did some testing and found out that using cookies of a yt premium account doesn't give errors, while without cookies or with the cookies of a non premium account it gives the 403 error
> 
> I also tried with the premium account and it works without any error.

If I become a YouTube Premium member, can I use the account's cookies to enable ytdl-related functions properly? Will these functions work normally in a Next.js environment?
